package com.project.nisum.app.models;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;

import java.util.UUID;

/**
 * Phone is an entity class representing a phone in the database.
 * It contains the phone's id, number, city code, country code, and the associated user.
 */
@Entity
@Getter
@Setter
@Table(name = "phones")
@Schema(description = "phone")
public class Phone {

    /**
     * The phone's id.
     * It is a UUID generated by the "UUID" generator.
     */
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator",
            parameters = {
                    @org.hibernate.annotations.Parameter(
                            name = "uuid_gen_strategy_class",
                            value = "org.hibernate.id.uuid.CustomVersionOneStrategy"
                    )
            }
    )
    private UUID id;

    /**
     * The phone's number.
     */
    private String number;

    /**
     * The phone's city code.
     */
    private String cityCode;

    /**
     * The phone's country code.
     */
    private String countryCode;

    /**
     * The user associated with the phone.
     * It is fetched lazily and joined on the "user_id" column.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;
}